[package]
name = "rs_wasmtime_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[profile.release]
# Optimize for size
opt-level = "s"

[build]
target = "wasm32-wasi"